apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-demo
  labels:
    app: drone-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: drone-demo
  template:
    metadata:
      labels:
        app: drone-demo
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
