apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
  labels:
    name: drone-demo
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: drone-demo
